/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostCommentRouteImport } from './routes/post-comment'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommentIndexRouteImport } from './routes/comment/index'
import { Route as CommentIdRouteImport } from './routes/comment/$id'

const PostCommentRoute = PostCommentRouteImport.update({
  id: '/post-comment',
  path: '/post-comment',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentIndexRoute = CommentIndexRouteImport.update({
  id: '/comment/',
  path: '/comment/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentIdRoute = CommentIdRouteImport.update({
  id: '/comment/$id',
  path: '/comment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/post-comment': typeof PostCommentRoute
  '/comment/$id': typeof CommentIdRoute
  '/comment': typeof CommentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/post-comment': typeof PostCommentRoute
  '/comment/$id': typeof CommentIdRoute
  '/comment': typeof CommentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/post-comment': typeof PostCommentRoute
  '/comment/$id': typeof CommentIdRoute
  '/comment/': typeof CommentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/not-found' | '/post-comment' | '/comment/$id' | '/comment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/not-found' | '/post-comment' | '/comment/$id' | '/comment'
  id:
    | '__root__'
    | '/'
    | '/not-found'
    | '/post-comment'
    | '/comment/$id'
    | '/comment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  PostCommentRoute: typeof PostCommentRoute
  CommentIdRoute: typeof CommentIdRoute
  CommentIndexRoute: typeof CommentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post-comment': {
      id: '/post-comment'
      path: '/post-comment'
      fullPath: '/post-comment'
      preLoaderRoute: typeof PostCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment/': {
      id: '/comment/'
      path: '/comment'
      fullPath: '/comment'
      preLoaderRoute: typeof CommentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment/$id': {
      id: '/comment/$id'
      path: '/comment/$id'
      fullPath: '/comment/$id'
      preLoaderRoute: typeof CommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  PostCommentRoute: PostCommentRoute,
  CommentIdRoute: CommentIdRoute,
  CommentIndexRoute: CommentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
