/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PostCommentRouteImport } from './routes/post-comment'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommentIndexRouteImport } from './routes/comment/index'
import { Route as CommentIdRouteImport } from './routes/comment/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PostCommentRoute = PostCommentRouteImport.update({
  id: '/post-comment',
  path: '/post-comment',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentIndexRoute = CommentIndexRouteImport.update({
  id: '/comment/',
  path: '/comment/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentIdRoute = CommentIdRouteImport.update({
  id: '/comment/$id',
  path: '/comment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/post-comment': typeof PostCommentRoute
  '/register': typeof RegisterRoute
  '/comment/$id': typeof CommentIdRoute
  '/comment': typeof CommentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/post-comment': typeof PostCommentRoute
  '/register': typeof RegisterRoute
  '/comment/$id': typeof CommentIdRoute
  '/comment': typeof CommentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/post-comment': typeof PostCommentRoute
  '/register': typeof RegisterRoute
  '/comment/$id': typeof CommentIdRoute
  '/comment/': typeof CommentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/post-comment'
    | '/register'
    | '/comment/$id'
    | '/comment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/post-comment'
    | '/register'
    | '/comment/$id'
    | '/comment'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/post-comment'
    | '/register'
    | '/comment/$id'
    | '/comment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  PostCommentRoute: typeof PostCommentRoute
  RegisterRoute: typeof RegisterRoute
  CommentIdRoute: typeof CommentIdRoute
  CommentIndexRoute: typeof CommentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-comment': {
      id: '/post-comment'
      path: '/post-comment'
      fullPath: '/post-comment'
      preLoaderRoute: typeof PostCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment/': {
      id: '/comment/'
      path: '/comment'
      fullPath: '/comment'
      preLoaderRoute: typeof CommentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment/$id': {
      id: '/comment/$id'
      path: '/comment/$id'
      fullPath: '/comment/$id'
      preLoaderRoute: typeof CommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  PostCommentRoute: PostCommentRoute,
  RegisterRoute: RegisterRoute,
  CommentIdRoute: CommentIdRoute,
  CommentIndexRoute: CommentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
